# Generated by Django 3.2.6 on 2021-08-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('author', models.CharField(blank=True, max_length=300, null=True)),
                ('year_of_publication', models.CharField(blank=True, max_length=300, null=True)),
                ('publisher', models.CharField(blank=True, max_length=300, null=True)),
                ('image_url_s', models.CharField(blank=True, max_length=300, null=True)),
                ('image_url_m', models.CharField(blank=True, max_length=300, null=True)),
                ('image_url_l', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
