# Generated by Django 3.2.6 on 2021-08-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='isbn',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
